spring:
  datasource:
    url: ${kyc.config.database.postgresql.url}
    username: ${kyc.config.database.postgresql.username}
    password: ${kyc.config.database.postgresql.secret}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

service:
  url: ${kyc.config.hostname}:9007/kyc/soap/

logging:
  file:
    name: /opt/kyc/logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: /opt/kyc/logs/${spring.application.name}/%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 50MB
      max-history: 30
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.springframework.ws: INFO
    org.springframework.ws.server.MessageTracing.sent: INFO
    org.springframework.ws.server.MessageTracing.received: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.StatementCreatorUtils: INFO

server:
  ssl:
    enabled: false
    key-store-type: PKCS12
    key-store: ${kyc.config.keystore.backbone.path}
    key-store-password: ${kyc.config.keystore.backbone.secret}
    key-alias: ${kyc.config.keystore.backbone.alias}